export enum BoardValuesEnum {
    UNREVEALED_EMPTY_POSITION = "E",
    UNREVEALED_MINE_POSITION = "M",
    BLANK_REVEALED_POSITION = "B",
    BOMB_REVEALED_POSITION = "X",
    MASKED_POSITION = "[]",
    BOMB_FLAGGED = "F",
    QUESTION_MARK = "?",
    RESET_POSITION = "R",
}